name: CI
on:
  push:
    branches:
      - master
    tags: ['*']
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
          - x86
        exclude:
          - os: macOS-latest
            arch: x86

    steps:
      - uses: actions/checkout@v4

      # Install Julia
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # Cache everything
      - uses: julia-actions/cache@v2

      # Run the tests
      - uses: julia-actions/julia-runtest@v1

      # Process coverage
      - uses: julia-actions/julia-processcoverage@v1

      # Upload coverage
      - uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
